spring.application.name=capacitaciones
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=archivos

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
